### ISSUE TITLE
Proportional valve control added

### ISSUE THREAD

**Issue by ahonxxx** [hausen8/ColdEND32#4]
Proportional valves are generally0-5V/4-20ma import

**Comment by hausen8** [comment]
The ColdEND control was developed precisely for this reason, because proportional valves do not guarantee an even flow. While their flow depends on the viscosity and thus on the temperature, a peristaltic pump always delivers the same amount under all conditions. A readjustment is therefore not necessary.

**Comment by ahonxxx** [comment]
hi 

![13131](https://user-images.githubusercontent.com/54906315/166849754-30075617-ee26-4c2a-aa79-bb0dbfc9a99c.png)


I'm talking about the manual pressure relief valve at the front air source becoming electrically controlled,

Coldend control station to control the size of the air
